# Generated by Django 4.1.1 on 2022-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_remove_review_review_alter_movie_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='reviews',
        ),
    ]
