# Generated by Django 4.1.1 on 2022-09-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_rename_movie_movie_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movie_app.review'),
        ),
    ]
